Repository devstoreproject/devstore, pull requests merged in 2023-09, with the labels that each got.

#190 [feat] 업로드 내용으로 상품 상세 표현
  FE/src/Components/CYW/ProductDetail/Tab/ProductTab/ProductTab.tsx
Labels: feat

#197 [feat] 카테고리, 장바구니, 리뷰 관리, 상품명 검색
  FE/src/App.tsx
  FE/src/Components/CYW/ProductDetail/ProductImg/ProductImg.tsx
  FE/src/Components/CYW/ProductDetail/ProductImg/SlideImg.tsx
  FE/src/Components/CYW/ProductDetail/ProductImg/SlideImgItem.tsx
  FE/src/Components/CYW/ProductDetail/ProductImg/TitleImg.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/Button.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/DeliveryInformation.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/OptionChoice.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/Price.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/ProductInformation.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/ProductName.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/SelectedResult.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryEditDeleteBtn.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewEditDeleteBtn.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewElement.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/UserReview.tsx
  FE/src/Components/CYW/RewiewManagement/AllReviewContents.tsx
  FE/src/Components/CYW/RewiewManagement/AllReviewManagement.tsx
  FE/src/Components/CYW/RewiewManagement/AllReviewTitle.tsx
  FE/src/Components/CYW/RewiewManagement/BestReviewContents.tsx
  FE/src/Components/CYW/RewiewManagement/BestReviewManagement.tsx
  FE/src/Components/CYW/RewiewManagement/BestReviewTitle.tsx
  FE/src/Components/CYW/Search/SearchItem.tsx
  FE/src/Components/CYW/Search/SearchList.tsx
  FE/src/Components/CYW/Search/SearchTool.tsx
  FE/src/Components/CYW/SearchCategory/CategoryItem.tsx
  FE/src/Components/CYW/SearchCategory/CategoryResult.tsx
  FE/src/Components/KHJ/Cart/CartItemOpt.tsx
  FE/src/Components/KHJ/Nav/GlobalNav.tsx
  FE/src/Pages/CYW/ProductDetail.tsx
  FE/src/Pages/CYW/Products.tsx
  FE/src/Pages/CYW/ReviewManagement.tsx
  FE/src/Pages/CYW/Search.tsx
Labels: feat

#205 Item Order 도메인 수정
  BE/backend/src/main/java/project/main/webstore/domain/cart/controller/CartController.java
  BE/backend/src/main/java/project/main/webstore/domain/cart/dto/CartGetResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/cart/dto/CartPatchRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/cart/entity/CartItem.java
  BE/backend/src/main/java/project/main/webstore/domain/cart/mapper/CartMapper.java
  BE/backend/src/main/java/project/main/webstore/domain/cart/service/CartService.java
  BE/backend/src/main/java/project/main/webstore/domain/item/controller/ItemController.java
  BE/backend/src/main/java/project/main/webstore/domain/item/entity/ItemOption.java
  BE/backend/src/main/java/project/main/webstore/domain/item/service/ItemService.java
  BE/backend/src/main/java/project/main/webstore/domain/order/dto/OrderLocalDto.java
  BE/backend/src/main/java/project/main/webstore/domain/order/dto/OrderPostDto.java
  BE/backend/src/main/java/project/main/webstore/domain/order/entity/Orders.java
  BE/backend/src/main/java/project/main/webstore/domain/order/service/OrderService.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/enums/QnaStatus.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/repository/QuestionRepository.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaGetService.java
  BE/backend/src/test/java/project/main/webstore/domain/qna/controller/QnaControllerTest.java
Labels: fit

#207 상품 수정 페이지 구현 및 상품 등록 페이지, 메인(랜딩) 페이지 수정
  FE/src/App.tsx
  FE/src/Components/LSM/Main/BestProduct/BestItem.tsx
  FE/src/Components/LSM/Main/BestProduct/BestItemList.tsx
  FE/src/Components/LSM/Main/BestReview/ReviewItem.tsx
  FE/src/Components/LSM/Main/NewProduct/NewItem.tsx
  FE/src/Components/LSM/Main/NewProduct/NewItemList.tsx
  FE/src/Components/LSM/Main/ThemeProduct/ThemeItem.tsx
  FE/src/Components/LSM/Product/ProductForm/Button.tsx
  FE/src/Components/LSM/Product/ProductForm/CategoryInput.tsx
  FE/src/Components/LSM/Product/ProductForm/ContentsInput.tsx
  FE/src/Components/LSM/Product/ProductForm/ImageInput.tsx
  FE/src/Components/LSM/Product/ProductForm/OptionInput.tsx
  FE/src/Components/LSM/Product/ProductForm/OrderInput.tsx
  FE/src/Components/LSM/Product/ProductForm/PriceInput.tsx
  FE/src/Components/LSM/Product/ProductForm/ProductForm.tsx
  FE/src/Components/LSM/Product/ProductForm/Select.tsx
  FE/src/Components/LSM/Product/ProductForm/TitleInput.tsx
  FE/src/Components/LSM/Product/ProductTitle.tsx
  FE/src/Pages/LSM/Main.tsx
  FE/src/Pages/LSM/Product/ProductEdit.tsx
  FE/src/Pages/LSM/Product/ProductPost.tsx
  FE/src/model/redux.ts
  FE/src/store/modules/setOptionId.ts
  FE/src/store/store.ts
Labels: fit, feat

#206 [feat] 카트 기능 완성, 주문내역페이지 완성
  FE/src/App.tsx
  FE/src/Components/KHJ/Cart/CartItem.tsx
  FE/src/Components/KHJ/Cart/CartItemOpt.tsx
  FE/src/Components/KHJ/Order/OrderItem.tsx
  FE/src/Components/KHJ/Purchase/DeliverForm.tsx
  FE/src/Components/KHJ/Purchase/DeliverReadonly.tsx
  FE/src/Components/KHJ/Type/OrderItemTypes.tsx
  FE/src/Pages/KHJ/Exchange.tsx
  FE/src/Pages/KHJ/OrderCom.tsx
  FE/src/Pages/KHJ/OrderComDetail.tsx
  FE/src/Pages/KHJ/PurComDetail.tsx
  FE/src/Pages/KHJ/PurComplete.tsx
Labels: feat

#209 Feat/fe/cyw
  FE/src/Components/CYW/ProductDetail/ProductInformation/OptionChoice.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/ProductInformation.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryTab.tsx
  FE/src/Components/CYW/ProductDetail/Tab/PaginationContainer.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/PaginationContainer.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewTab.tsx
  FE/src/Components/CYW/ProductDetail/Tab/Tab.tsx
  FE/src/utils/productDetail/fetchInquiry.ts
  FE/src/utils/productDetail/fetchReview.ts
  FE/src/utils/sales/calculateTotalSales.ts
Labels: feat, fix, design

#213 [refactor] 간결하게 코드 수정
  FE/src/Components/CYW/Search/SearchList.tsx
Labels: fit

#215 관리자 페이지 상품 리스트 내 수정 버튼, 메인 랜딩 페이지 네비게이터 수정
  FE/src/Components/KYH/admin/ProductList/OrderListBtnContainer.tsx
  FE/src/Components/LSM/Main/BestProduct/BestItem.tsx
  FE/src/Components/LSM/Main/BestReview/ReviewItem.tsx
  FE/src/Components/LSM/Main/BestReview/ReviewItemList.tsx
  FE/src/Components/LSM/Main/NewProduct/NewItem.tsx
  FE/src/Components/LSM/Main/ThemeProduct/ThemeItemList.tsx
Labels: fit, fix

#216 메인 랜딩 페이지 네비게이터 수정
  FE/src/Components/LSM/Main/ThemeProduct/ThemeItem.tsx
  FE/src/Components/LSM/Main/ThemeProduct/ThemeItemList.tsx
Labels: fit, fix

#217 메인 랜딩페이지 네비게이터 수정
  FE/src/Components/LSM/Main/ThemeProduct/ThemeItem.tsx
Labels: fit, fix

#219 상품 수정 페이지 수정
  FE/src/Pages/LSM/Product/ProductEdit.tsx
Labels: fit, fix

#221 결제 API 구현
  BE/backend/src/main/java/project/main/webstore/domain/payment/controller/PaymentController.java
  BE/backend/src/main/java/project/main/webstore/domain/payment/dto/PrePareDto.java
  BE/backend/src/main/java/project/main/webstore/domain/payment/dto/PrePareResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/payment/service/PaymentService.java
  BE/backend/src/main/resources/application.yml
Labels: enhancement
