Repository devstoreproject/devstore, pull requests merged in 2023-08, with the labels that each got.

#81 로직 수정 완료
  BE/backend/src/main/java/project/main/webstore/domain/item/dto/OptionResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetSimpleResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticePostRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionDto.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Question.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/exception/QnaExceptionCode.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
  BE/backend/src/main/java/project/main/webstore/security/AuthController.java
  BE/backend/src/main/java/project/main/webstore/security/dto/LoginDto.java
  BE/backend/src/main/java/project/main/webstore/security/jwt/filter/JwtAuthenticationFilter.java
Labels: fit

#122 Swagger 그룹 분리 1차 완성
  BE/backend/src/main/java/project/main/webstore/config/SwaggerConfig.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/controller/NoticeController.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetSimpleResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/enums/NoticeCategory.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/mapper/NoticeMapper.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeGetService.java
  BE/backend/src/main/java/project/main/webstore/domain/orderHistory/entity/OrderHistory.java
  BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewUpdateRequestDto.java
  BE/backend/src/main/java/project/main/webstore/security/AuthController.java
  BE/backend/src/main/java/project/main/webstore/utils/FileUploader.java
  BE/backend/src/main/resources/application.yml
  BE/backend/src/test/java/project/main/webstore/domain/review/stub/ReviewStub.java
Labels: documentation

#123 userAPI 추가 구현
  BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
  BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserGetPasswordRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserGetPasswordResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
  BE/backend/src/main/java/project/main/webstore/domain/users/mapper/UserMapper.java
  BE/backend/src/main/java/project/main/webstore/domain/users/repository/UserRepository.java
  BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
  BE/backend/src/main/java/project/main/webstore/email/enums/CheckCondition.java
  BE/backend/src/main/java/project/main/webstore/email/event/UserRegistrationApplicationEvent.java
  BE/backend/src/main/java/project/main/webstore/email/event/UserRegistrationEventListener.java
  BE/backend/src/main/java/project/main/webstore/security/AuthController.java
  BE/backend/src/main/resources/application.yml
Labels: enhancement

#126 구글 OAuth2 설정 완료
  BE/backend/src/main/java/project/main/webstore/config/OauthConfig.java
  BE/backend/src/main/java/project/main/webstore/config/SecurityConfig.java
  BE/backend/src/main/java/project/main/webstore/config/SwaggerConfig.java
  BE/backend/src/main/java/project/main/webstore/config/javaConfig.java
  BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
  BE/backend/src/main/java/project/main/webstore/domain/users/enums/ProviderId.java
  BE/backend/src/main/java/project/main/webstore/domain/users/repository/UserRepository.java
  BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
  BE/backend/src/main/java/project/main/webstore/exception/CommonExceptionCode.java
  BE/backend/src/main/java/project/main/webstore/security/oauth2/handler/OAuth2UserSuccessHandler.java
  BE/backend/src/main/resources/application.yml
Labels: enhancement

#127 제품 정보, 문의, 리뷰 불러오기 등 카테고리 페이지에서 해당 제품 페이지 이동
  FE/src/App.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/AnswerElement.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryElement.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryTab.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/UserInquiry.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ProductTab/ProductTab.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewElement.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewTab.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/UserInfo.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/UserReview.tsx
  FE/src/Components/CYW/ProductDetail/Tab/Tab.tsx
  FE/src/Components/CYW/SearchCategory/CategoryItem.tsx
  FE/src/Components/CYW/SearchCategory/CategoryResult.tsx
  FE/src/Components/CYW/SearchCategory/ResultItem.tsx
  FE/src/Pages/CYW/SearchCategory.tsx
  FE/src/utils/productDetail/fetchInquiry.ts
  FE/src/utils/productDetail/fetchReview.ts
Labels: fit, feat

#129 공지사항 메인(리스트) 페이지 기능 구현
  FE/src/App.tsx
  FE/src/Components/LSM/Notice/NoticeList/ContentsItem.tsx
  FE/src/Components/LSM/Notice/NoticeList/ContentsList.tsx
  FE/src/Components/LSM/Notice/NoticeList/TabList.tsx
  FE/src/Components/LSM/Notice/NoticeList/TabListItem.tsx
  FE/src/Pages/LSM/Notice/NoticeList.tsx
Labels: feat

#131 마일리지 제거 완료
  BE/backend/src/main/java/project/main/webstore/domain/item/dto/ItemPatchDto.java
  BE/backend/src/main/java/project/main/webstore/domain/item/dto/ItemPostDto.java
  BE/backend/src/main/java/project/main/webstore/domain/item/entity/Item.java
  BE/backend/src/main/java/project/main/webstore/domain/item/service/ItemService.java
  BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserOrderDto.java
  BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
  BE/backend/src/main/java/project/main/webstore/security/oauth2/handler/OAuth2UserSuccessHandler.java
Labels: fit

#133 공지사항 메인(리스트) 페이지 수정
  FE/src/Components/LSM/Notice/NoticeList/ContentsItem.tsx
  FE/src/Components/LSM/Notice/NoticeList/ContentsList.tsx
  FE/src/Pages/LSM/Notice/NoticeList.tsx
Labels: feat, design

#134 공지사항 메인(리스트) 페이지 수정
  FE/src/Pages/LSM/Notice/NoticeList.tsx
Labels: fit

#136 공지사항 메인(리스트) 페이지 수정
  FE/src/App.tsx
  FE/src/Components/KYH/admin/MenuNav.tsx
  FE/src/Components/LSM/Notice/NoticeList/ContentsItem.tsx
  FE/src/Components/LSM/Notice/NoticeList/ContentsList.tsx
  FE/src/Components/LSM/Notice/NoticeList/TabList.tsx
  FE/src/Components/LSM/Notice/NoticeList/TabListItem.tsx
  FE/src/Pages/LSM/Notice/NoticeList.tsx
Labels: feat, design

#137 공지사항 상세/등록/수정 페이지 수정
  FE/src/Components/KYH/admin/MenuNav.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/Contents.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/Date.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/IconButton.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/ImageBox.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/TabTitle.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/Title.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Button.tsx
  FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Textarea.tsx
  FE/src/Components/LSM/Notice/NoticeForm/TitleInput.tsx
  FE/src/Components/LSM/Notice/NoticeList/IconButton.tsx
  FE/src/Components/LSM/Notice/NoticeTitle.tsx
  FE/src/Components/LSM/Product/ProductForm/ImageInput.tsx
  FE/src/Pages/LSM/Notice/NoticeDetail.tsx
  FE/src/Pages/LSM/Notice/NoticeEdit.tsx
  FE/src/Pages/LSM/Notice/NoticeList.tsx
  FE/src/Pages/LSM/Notice/NoticePost.tsx
Labels: fit, feat, design

#138 공지사항 등록 페이지 수정
  FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
Labels: feat

#139 공지사항 등록 페이지 수정, 수정 페이지 일부 수정
  FE/src/Components/LSM/Notice/NoticeForm/Button.tsx
  FE/src/Components/LSM/Notice/NoticeForm/ImageInput.tsx
  FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
  FE/src/Components/LSM/Notice/NoticeForm/TitleInput.tsx
  FE/src/Pages/LSM/Notice/NoticeEdit.tsx
  FE/src/Pages/LSM/Notice/NoticePost.tsx
Labels: fit, feat, design

#142 공지사항 수정 페이지 수정
  FE/src/App.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/IconButton.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/ImageBox.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/TabTitle.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Button.tsx
  FE/src/Components/LSM/Notice/NoticeForm/ImageInput.tsx
  FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
  FE/src/Components/LSM/Notice/NoticeForm/Textarea.tsx
  FE/src/Components/LSM/Notice/NoticeForm/TitleInput.tsx
  FE/src/Components/LSM/Notice/NoticeTitle.tsx
  FE/src/Pages/LSM/Notice/NoticeDetail.tsx
  FE/src/Pages/LSM/Notice/NoticeEdit.tsx
  FE/src/Pages/LSM/Notice/NoticePost.tsx
Labels: fit, feat

#143 QnA 구현 및 리펙토링 완료
  BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
  BE/backend/src/main/java/project/main/webstore/domain/notice/mapper/NoticeMapper.java
  BE/backend/src/main/java/project/main/webstore/domain/order/entity/Orders.java
  BE/backend/src/main/java/project/main/webstore/domain/order/enums/OrderedItem.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPostRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Answer.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Question.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/mapper/QnaMapper.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaGetService.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaValidService.java
  BE/backend/src/main/java/project/main/webstore/domain/users/service/UserValidService.java
  BE/backend/src/main/java/project/main/webstore/utils/UriCreator.java
  BE/backend/src/test/java/project/main/webstore/annotation/WithMockCustomUser.java
  BE/backend/src/test/java/project/main/webstore/annotation/WithMockCustomUserSecurityContextFactory.java
  BE/backend/src/test/java/project/main/webstore/domain/order/stub/OrderStub.java
  BE/backend/src/test/java/project/main/webstore/domain/qna/controller/QnaControllerTest.java
  BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaServiceTest.java
  BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaValidServiceTest.java
  BE/backend/src/test/java/project/main/webstore/domain/qna/stub/QnaStub.java
  BE/backend/src/test/java/project/main/webstore/helper/TestUtils.java
  BE/backend/src/test/java/project/main/webstore/totalTest/NoticeControllerTest.java
  BE/backend/src/test/java/project/main/webstore/totalTest/QnaControllerTest.java
Labels: enhancement

#146 공지사항 상세 페이지 수정
  FE/src/Components/LSM/Notice/NoticeDetail/IconButton.tsx
  FE/src/Components/LSM/Notice/NoticeDetail/TabTitle.tsx
  FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
  FE/src/Pages/LSM/Notice/NoticeDetail.tsx
Labels: fit, fix

#149 Review 리펙토링 및 Test 구현
  BE/backend/src/main/java/project/main/webstore/domain/image/utils/ImageUtils.java
  BE/backend/src/main/java/project/main/webstore/domain/item/exception/ItemExceptionCode.java
  BE/backend/src/main/java/project/main/webstore/domain/item/service/ItemService.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
  BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaValidService.java
  BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewBestRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewBestResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewLikeResponseDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewUpdateRequestDto.java
  BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
  BE/backend/src/main/java/project/main/webstore/domain/review/mapper/ReviewMapper.java
  BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
  BE/backend/src/main/java/project/main/webstore/domain/users/service/UserValidService.java
  BE/backend/src/main/java/project/main/webstore/security/AuthController.java
  BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaServiceTest.java
  BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaValidServiceTest.java
  BE/backend/src/test/java/project/main/webstore/domain/review/controller/ReviewControllerTest.java
  BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
  BE/backend/src/test/java/project/main/webstore/domain/review/stub/ReviewStub.java
  BE/backend/src/test/java/project/main/webstore/helper/TestUtils.java
  BE/backend/src/test/java/project/main/webstore/stub/ImageStub.java
  BE/backend/src/test/java/project/main/webstore/totalTest/ReviewControllerTest.java
Labels: enhancement

#173 [fix] 타입에러 코드 수정
  FE/src/Pages/LSM/Notice/NoticeList.tsx
Labels: fix

#150 장바구니 기능구현 완료
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/Components/KHJ/Cart/CartItem.tsx
  FE/src/Components/KHJ/Cart/CartItemOpt.tsx
  FE/src/Components/KHJ/Cart/CartMain.tsx
  FE/src/Components/KHJ/Purchase/Delivery.tsx
  FE/src/Components/KHJ/Purchase/PayProgress.tsx
  FE/src/Components/KHJ/Type/CartTypes.tsx
  FE/src/Pages/KHJ/Cart.tsx
  FE/src/Pages/KHJ/Purchase.tsx
Labels: feat

#168 [feat] 좋아요, 문의, 리뷰 관련 기능 추가
  FE/src/App.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/Button.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/DeliveryInformation.tsx
  FE/src/Components/CYW/ProductDetail/ProductInformation/ProductInformation.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryEditDeleteBtn.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryElement.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryTab.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewElement.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewRegister.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/ReviewTab.tsx
  FE/src/Components/CYW/ProductDetail/Tab/ReviewTab/UserReview.tsx
  FE/src/Components/CYW/ProductDetail/Tab/Tab.tsx
  FE/src/Components/CYW/SearchCategory/CategoryItem.tsx
  FE/src/Components/CYW/SearchCategory/CategoryResult.tsx
  FE/src/Pages/CYW/ProductDetail.tsx
  FE/src/Pages/CYW/Products.tsx
  FE/src/utils/productDetail/fetchInquiry.ts
  FE/src/utils/productDetail/fetchReview.ts
Labels: fit, feat, design

#186 [design] UI 수정
  FE/src/Components/LSM/Main/BestProduct/BestItem.tsx
  FE/src/Components/LSM/Main/BestProduct/BestItemList.tsx
  FE/src/Components/LSM/Main/NewProduct/NewItem.tsx
  FE/src/Components/LSM/Main/NewProduct/NewItemList.tsx
  FE/src/Pages/LSM/Main.tsx
  FE/src/Pages/LSM/Notice/NoticeList.tsx
Labels: fit
